import type { Metadata } from "next";
import { mazzardSoft } from "@/fonts";
import "./globals.css";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mazzardSoft.variable} antialiased min-h-screen flex flex-col`}
        style={{ background: '#E2E2E2' }}
      >
        <div className="flex-grow">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
